name: CI
on: [push, pull_request]

jobs:
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party build tools
        run: |
          sudo apt-get update
          sudo apt-get install make clang libsdl2-dev libsdl2-ttf-dev 
      - name: build all and examples
        run: |
          make
        env:
          CC: clang
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: download sdl2
        run: |
          curl -fsSL -o SDL2-devel-VC.zip https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip
          7z x SDL2-devel-VC.zip
          mv SDL2-2.0.14 SDL2
          curl -fsSL -o SDL2_ttf-VC.zip https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip
          7z x SDL2_ttf-devel-VC.zip
          mv SDL2_ttf-devel-2.0.15 SDL2_ttf
      - name: build all and examples
        shell: cmd
        # this replaces default PowerShell, which can't fail the build
        run: |
          ./build_msvc.bat
