name: CI
on: [push, pull_request]

jobs:
  makerelease:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: true

  build-linux-clang:
    runs-on: ubuntu-latest
    needs: makerelease
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party build tools
        run: |
          sudo apt-get update
          sudo apt-get install make clang libsdl2-dev libsdl2-ttf-dev 
      - name: build all and examples
        run: |
          make dist
          7z a linux64.zip out
        env:
          CC: clang
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.makerelease.outputs.upload_url }}
          asset_path: linux64.zip
          asset_name: linux64-${{ github.sha }}.zip
          asset_content_type: application/zip
  build-windows-msvc:
    runs-on: windows-2019
    needs: makerelease
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: download sdl2
        run: |
          curl -fsSL -o SDL2-devel-VC.zip https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip
          7z x SDL2-devel-VC.zip
          mv SDL2-2.0.14 SDL2
          curl -fsSL -o SDL2_ttf-VC.zip https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip
          7z x SDL2_ttf-VC.zip
          mv SDL2_ttf-2.0.15 SDL2_ttf
      - name: build all and examples
        run: |
          ./build_msvc.bat
          7z a win64.zip out
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.makerelease.outputs.upload_url }}
          asset_path: win64.zip
          asset_name: win64-${{ github.sha }}.zip
          asset_content_type: application/zip
